version: "3.2"
services:

  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Plaintext123!"
      ACCEPT_EULA: "Y"